(defvar x-select-enable-clipboard nil)
(require 'time)
(require 'longlines)
(require 'uniquify)
(require 'cus-edit)
(require 'complete)
(require 'desktop)
(require 'ring)
(require 'comint)
(require 'completion)
(require 'gnus-group)
(require 'gnus-async)
(require 'gnus-sum)
(require 'gnus-score)
(require 'calendar)
(load "w32-vars" t t)

(byte-compile-file "~/EliEmacs/eliemacs.el")
